# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mainapp-llmworker.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'mainapp-llmworker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17mainapp-llmworker.proto\",\n\x11NewMessageRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\x05\"\x1a\n\nTokenChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\nCompletion\x12\x11\n\tfull_text\x18\x01 \x01(\t\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x95\x01\n\x17NewMessageChunkResponse\x12\x1c\n\x05token\x18\x01 \x01(\x0b\x32\x0b.TokenChunkH\x00\x12!\n\ncompletion\x18\x02 \x01(\x0b\x32\x0b.CompletionH\x00\x12\x17\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x06.ErrorH\x00\x12\x17\n\x0f\x63onversation_id\x18\x04 \x01(\x05\x42\x07\n\x05\x65vent2Q\n\x0eMessageService\x12?\n\rGenerateReply\x12\x12.NewMessageRequest\x1a\x18.NewMessageChunkResponse0\x01\x42\x16\xaa\x02\x13MainApp.Grpc.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mainapp_llmworker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023MainApp.Grpc.Protos'
  _globals['_NEWMESSAGEREQUEST']._serialized_start=27
  _globals['_NEWMESSAGEREQUEST']._serialized_end=71
  _globals['_TOKENCHUNK']._serialized_start=73
  _globals['_TOKENCHUNK']._serialized_end=99
  _globals['_COMPLETION']._serialized_start=101
  _globals['_COMPLETION']._serialized_end=132
  _globals['_ERROR']._serialized_start=134
  _globals['_ERROR']._serialized_end=158
  _globals['_NEWMESSAGECHUNKRESPONSE']._serialized_start=161
  _globals['_NEWMESSAGECHUNKRESPONSE']._serialized_end=310
  _globals['_MESSAGESERVICE']._serialized_start=312
  _globals['_MESSAGESERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
